[PATHS]
temp_dir = R:\temp_chunks
ready_dir = D:\AutoDownloadDVR\ready_videos

[FFMPEG]
# Основная команда (копируем видео и аудио)
default_args = -y -f concat -safe 0 -c:v copy -c:a copy
# Команда спасения (копируем видео, вырезаем битое аудио параметром -an)
fallback_args = -y -f concat -safe 0 -c:v copy -an